SET SERVEROUTPUT ON
/*DECLARE
    v_Salario NUMBER;
    v_FirstName EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME, SALARY INTO v_FirstName, v_Salario
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=100;
    
    DBMS_OUTPUT.PUT_LINE('Nombre '||v_Firstname||' Salario '|| v_Salario);
    
END;
/*/

SELECT * FROM DUAL;
DESC DUAL;
SELECT 'hola' FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;
SELECT USER FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) "Mes" FROM DUAL;