create or replace FUNCTION GetEmail RETURN VARCHAR
AS
email VARCHAR(30);
mes NUMBER;
dia NUMBER;
segundos NUMBER;
minutos NUMBER;
BEGIN
SELECT EXTRACT(MONTH FROM SYSTIMESTAMP)INTO mes FROM DUAL;
SELECT EXTRACT(DAY FROM SYSTIMESTAMP) INTO dia FROM DUAL;
SELECT EXTRACT(MINUTE FROM SYSTIMESTAMP) INTO minutos FROM DUAL;
SELECT EXTRACT(SECOND FROM SYSTIMESTAMP) INTO segundos FROM DUAL;
segundos:=TRUNC(segundos,0);
email:=dia||'-'||mes||'-'||minutos||'-'||segundos||'@gmail.com';

RETURN email;
END;